input.onButtonPressed(Button.A, function () {
    DeskBit.Run(DIR.runForward, 100)
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(330, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    music.playTone(262, music.beat(BeatFraction.Whole))
    DeskBit.Run(DIR.runBack, 100)
    music.playTone(294, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    music.playTone(220, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    DeskBit.Run(DIR.runForward, 100)
    music.playTone(330, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    music.playTone(294, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Indigo))
    music.playTone(262, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Violet))
    music.playTone(294, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Purple))
    music.playTone(220, music.beat(BeatFraction.Double))
    DeskBit.Run(DIR.leftRotation, 100)
    music.playTone(330, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.White))
    music.playTone(262, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(294, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    music.playTone(294, music.beat(BeatFraction.Whole))
    DeskBit.Run(DIR.rightRotation, 100)
    music.playTone(392, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    music.playTone(330, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    music.playTone(247, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    music.playTone(262, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Indigo))
    DeskBit.Run(DIR.leftRotation, 100)
    music.playTone(262, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Violet))
    music.playTone(247, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Purple))
    music.playTone(220, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.White))
    music.playTone(247, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    music.playTone(262, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    DeskBit.Run(DIR.rightRotation, 100)
    music.playTone(294, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.White))
    music.playTone(196, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    music.playTone(440, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    music.playTone(392, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Indigo))
    DeskBit.Run(DIR.rightRotation, 100)
    music.playTone(330, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Violet))
    music.playTone(330, music.beat(BeatFraction.Double))
    strip.showColor(neopixel.colors(NeoPixelColors.Purple))
    DeskBit.Run(DIR.leftRotation, 100)
    music.playTone(294, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    music.playTone(262, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.White))
    music.playTone(294, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    music.playTone(330, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Yellow))
    music.playTone(294, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    music.playTone(330, music.beat(BeatFraction.Quarter))
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    music.playTone(392, music.beat(BeatFraction.Quarter))
    strip.showColor(neopixel.colors(NeoPixelColors.Indigo))
    music.playTone(392, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Violet))
    DeskBit.Run(DIR.runForward, 100)
    music.playTone(392, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Purple))
    music.playTone(392, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    music.playTone(392, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Violet))
    music.playTone(392, music.beat(BeatFraction.Half))
    strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    music.playTone(392, music.beat(BeatFraction.Whole))
    strip.showColor(neopixel.colors(NeoPixelColors.Black))
    DeskBit.Stop()
})
let strip: neopixel.Strip = null
basic.showIcon(IconNames.Happy)
strip = neopixel.create(DigitalPin.P0, 5, NeoPixelMode.RGB)
